ARG BASE_IMAGE=debian:unstable

# Stage 1: Build
FROM ${BASE_IMAGE} AS build

ARG SSL=openssl
ARG BUILD_TYPE=debug
ARG SHMEM=true
ARG DEBIAN_FRONTEND=noninteractive

RUN \
	apt-get update && \
	apt-get install -qq -y --no-install-recommends \
		build-essential \
		ca-certificates \
		cmake \
		git \
		libconfig-dev \
		libprotobuf-c-dev \
		pkg-config

RUN \
	if test "${SSL}" = "gnutls" ; then \
		apt-get install -qq -y --no-install-recommends libgnutls28-dev ; \
	fi && \
	if test "${SSL}" = "mbedtls" ; then \
		apt-get install -qq -y --no-install-recommends libmbedtls-dev ; \
	fi && \
	if test "${SSL}" = "openssl" ; then \
		apt-get install -qq -y --no-install-recommends libssl-dev ; \
	fi && \
	echo "SSL=${SSL}"

WORKDIR /umurmur

COPY CMakeLists.txt .
COPY cmake cmake
COPY umurmur.conf.example .
COPY src src

RUN \
	cmake -Bbuild-${SSL} -H. \
		-DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
		-DCMAKE_INSTALL_BINDIR=bin \
		-DUSE_SHAREDMEMORY_API=${SHMEM} \
		-DSSL=${SSL} && \
	cmake --build build-${SSL} && \
	cmake --install build-${SSL}

# Stage 2: Runtime
FROM ${BASE_IMAGE}

ARG SSL=openssl
ARG DEBIAN_FRONTEND=noninteractive

RUN \
	apt-get update && \
	apt-get install -qq -y --no-install-recommends \
		libconfig-dev \
		libprotobuf-c1 && \
	if test "${SSL}" = "gnutls" ; then \
		apt-get install -qq -y --no-install-recommends libgnutls28-dev ; \
	fi && \
	if test "${SSL}" = "mbedtls" ; then \
		apt-get install -qq -y --no-install-recommends \
			libmbedtls-dev ; \
	fi && \
	if test "${SSL}" = "mbedtls" ; then \
		apt-get install -qq -y --no-install-recommends \
			libmbedtls21 libmbedx509-7 libmbedcrypto16 ; \
	fi && \
	if test "${SSL}" = "openssl" ; then \
		apt-get install -qq -y --no-install-recommends libssl-dev ; \
	fi && \
	rm -rf /var/lib/apt/lists/* && \
	mkdir /etc/umurmur

COPY --from=build /usr/local/bin/umurmurd /usr/local/bin/
COPY --from=build /umurmur/umurmur.conf.example /usr/local/etc/umurmur/umurmur.conf

EXPOSE 64738

ENTRYPOINT ["/usr/local/bin/umurmurd", "-d"]
