/* Copyright (C) 2015-2016, Felix Morgner <felix.morgner@gmail.com>

   All rights reserved.

   Redistribution and use in source and binary forms, with or without
   modification, are permitted provided that the following conditions
   are met:

   - Redistributions of source code must retain the above copyright notice,
     this list of conditions and the following disclaimer.
   - Redistributions in binary form must reproduce the above copyright notice,
     this list of conditions and the following disclaimer in the documentation
     and/or other materials provided with the distribution.
   - Neither the name of the Developers nor the names of its contributors may
     be used to endorse or promote products derived from this software without
     specific prior written permission.

   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
   ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
   LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
   A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR
   CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
   EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
   PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
   PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
   LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
   NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#include "ssl.h"
#include "conf.h"
#include "log.h"
#include "memory.h"

#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <time.h>

#include <gnutls/x509.h>

static gnutls_certificate_credentials_t certificate;

static const char * ciphers = "NONE:"
							  "+ECDHE-ECDSA:+ECDHE-RSA:+RSA:"
							  "+AES-256-GCM:+AES-128-GCM:"
							  "+AEAD:+SHA384:+SHA256:+SHA1:"
							  "+CURVE-ALL:"
							  "+COMP-NULL:"
							  "+SIGN-ALL:"
							  "+VERS-TLS1.2:+VERS-TLS1.0:"
							  "+CTYPE-X509";

static gnutls_priority_t cipherCache;

static bool_t file_exists(const char *filename)
{
	return (access(filename, F_OK) == 0);
}

static void write_pem_file(const char *path, const gnutls_datum_t *pem)
{
	FILE *fp = fopen(path, "w");
	if (fp == NULL) {
		Log_warn("Unable to open %s for writing", path);
		return;
	}
	if (fwrite(pem->data, 1, pem->size, fp) != pem->size)
		Log_warn("Unable to write %s", path);
	fclose(fp);
}

static time_t cert_not_after(time_t now)
{
	struct tm t, *tm;

	tm = gmtime(&now);
	if (tm == NULL)
		return (time_t)-1;
	t = *tm;
	if (t.tm_mon == 1 && t.tm_mday == 29)
		t.tm_mday = 28;
	t.tm_year += 20;
	return timegm(&t);
}

static void generate_cert_and_key(const char *keyfile, const char *crtfile)
{
	gnutls_x509_crt_t crt = NULL;
	gnutls_x509_privkey_t pkey = NULL;
	gnutls_datum_t cert_pem = { NULL, 0 };
	gnutls_datum_t key_pem = { NULL, 0 };
	unsigned char serial = 1, skid[32];
	size_t skid_size = sizeof(skid);
	time_t now, exp;
	int rc;

	Log_info("Generating new server certificate.");

	now = time(NULL);
	exp = cert_not_after(now);
	if (exp == (time_t)-1) {
		rc = GNUTLS_E_INTERNAL_ERROR;
		goto err;
	}

	if ((rc = gnutls_x509_privkey_init(&pkey)) != GNUTLS_E_SUCCESS)
		goto err;
	if ((rc = gnutls_x509_privkey_generate(pkey, GNUTLS_PK_RSA, 2048, 0)) != GNUTLS_E_SUCCESS)
		goto err;

	if ((rc = gnutls_x509_crt_init(&crt)) != GNUTLS_E_SUCCESS)
		goto err;
	if ((rc = gnutls_x509_crt_set_version(crt, 3)) != GNUTLS_E_SUCCESS)
		goto err;
	if ((rc = gnutls_x509_crt_set_serial(crt, &serial, 1)) != GNUTLS_E_SUCCESS)
		goto err;
	if ((rc = gnutls_x509_crt_set_activation_time(crt, now)) != GNUTLS_E_SUCCESS)
		goto err;
	if ((rc = gnutls_x509_crt_set_expiration_time(crt, exp)) != GNUTLS_E_SUCCESS)
		goto err;
	if ((rc = gnutls_x509_crt_set_key(crt, pkey)) != GNUTLS_E_SUCCESS)
		goto err;
	if ((rc = gnutls_x509_crt_set_dn(crt, "CN=Murmur Autogenerated Certificate v2", NULL)) != GNUTLS_E_SUCCESS)
		goto err;
	if ((rc = gnutls_x509_crt_set_issuer_dn(crt, "CN=Murmur Autogenerated Certificate v2", NULL)) != GNUTLS_E_SUCCESS)
		goto err;
	if ((rc = gnutls_x509_crt_set_basic_constraints(crt, 0, 0)) != GNUTLS_E_SUCCESS)
		goto err;
	if (gnutls_x509_crt_get_key_id(crt, 0, skid, &skid_size) == GNUTLS_E_SUCCESS)
		gnutls_x509_crt_set_subject_key_id(crt, skid, skid_size);
	if ((rc = gnutls_x509_crt_sign2(crt, crt, pkey, GNUTLS_DIG_SHA256, 0)) != GNUTLS_E_SUCCESS)
		goto err;

	if ((rc = gnutls_certificate_set_x509_key(certificate, &crt, 1, pkey)) != GNUTLS_E_SUCCESS)
		goto err;

	if ((rc = gnutls_x509_crt_export2(crt, GNUTLS_X509_FMT_PEM, &cert_pem)) != GNUTLS_E_SUCCESS)
		goto err;
	if ((rc = gnutls_x509_privkey_export2(pkey, GNUTLS_X509_FMT_PEM, &key_pem)) != GNUTLS_E_SUCCESS)
		goto err;
	write_pem_file(crtfile, &cert_pem);
	write_pem_file(keyfile, &key_pem);

	gnutls_free(cert_pem.data);
	gnutls_free(key_pem.data);
	gnutls_x509_crt_deinit(crt);
	gnutls_x509_privkey_deinit(pkey);
	return;
err:
	gnutls_free(cert_pem.data);
	gnutls_free(key_pem.data);
	if (crt)
		gnutls_x509_crt_deinit(crt);
	if (pkey)
		gnutls_x509_privkey_deinit(pkey);
	Log_fatal("Failed to generate key and/or certificate: %s", gnutls_strerror(rc));
}

void initializeCertificate()
{
	const char *certificatePath = getStrConf(CERTIFICATE);
	const char *keyPath = getStrConf(KEY);
	int error;

	if (!certificatePath)
		Log_fatal("No certificate file specified.");
	if (!keyPath)
		Log_fatal("No key file specified");

	gnutls_certificate_allocate_credentials(&certificate);

	error = gnutls_certificate_set_x509_key_file(certificate, certificatePath, keyPath, GNUTLS_X509_FMT_PEM);
	if (error == GNUTLS_E_SUCCESS)
		return;

	/* Do not generate new certificate if either private key or
	 * certificate file (or both) already exists, even though one
	 * (or both) of them is invalid or inaccessible. */
	if (file_exists(keyPath) || file_exists(certificatePath))
		Log_fatal("Key and/or certificate file present but invalid or inaccessible. Exiting.");

	generate_cert_and_key(keyPath, certificatePath);
}

void SSLi_init()
{
	if(gnutls_priority_init(&cipherCache, ciphers, NULL) != GNUTLS_E_SUCCESS)
	{
		Log_fatal("Failed to set priorities");
	}

	initializeCertificate();

	Log_info("GnuTLS library initialized (version: %s)", gnutls_check_version(NULL));
}

void SSLi_deinit()
{
	gnutls_certificate_free_credentials(certificate);
	gnutls_priority_deinit(cipherCache);
	gnutls_global_deinit();
}

SSL_handle_t * SSLi_newconnection( int * fileDescriptor, bool_t * isSSLReady )
{
	gnutls_session_t * session
		= Memory_safeCalloc(1, sizeof(gnutls_session_t));

	gnutls_init(session, GNUTLS_SERVER);
	gnutls_priority_set(*session, cipherCache);
	gnutls_credentials_set(*session, GNUTLS_CRD_CERTIFICATE, certificate);

	gnutls_certificate_server_set_request(*session, GNUTLS_CERT_REQUIRE);

	gnutls_transport_set_int(*session, *fileDescriptor);

	if(isSSLReady && SSLi_nonblockaccept(session, isSSLReady))
		*isSSLReady = true;

	return session;
}

bool_t SSLi_getSHA1Hash(SSL_handle_t *session, uint8_t *hash)
{
	gnutls_datum_t const * certificateData = gnutls_certificate_get_peers(*session, NULL);

	size_t resultSize = 0;
	int error = gnutls_fingerprint( GNUTLS_DIG_SHA1, certificateData, hash, &resultSize);
	return error == GNUTLS_E_SUCCESS && resultSize == 20;
}

int SSLi_nonblockaccept( SSL_handle_t *session, bool_t * isSSLReady )
{
	int error;
	do {
		error = gnutls_handshake(*session);
	} while(error < GNUTLS_E_SUCCESS && !gnutls_error_is_fatal(error));

	if ( error < GNUTLS_E_SUCCESS ) {
		Log_warn("TLS handshake failed with error %i (%s).", error, gnutls_strerror(error));
	}

	if(isSSLReady)
		*isSSLReady = true;

	return error;
}

int SSLi_read(SSL_handle_t *session, uint8_t *buffer, int length)
{
	return gnutls_record_recv(*session, buffer, length);
}

int SSLi_write(SSL_handle_t *session, uint8_t *buffer, int length)
{
	return gnutls_record_send(*session, buffer, length);
}

int SSLi_get_error(SSL_handle_t *session, int code)
{
	(void)session;
	return code;
}

bool_t SSLi_data_pending(SSL_handle_t *session)
{
	return gnutls_record_check_pending(*session);
}

void SSLi_shutdown(SSL_handle_t *session)
{
	gnutls_bye(*session, GNUTLS_SHUT_WR);
}

void SSLi_free(SSL_handle_t *session)
{
	gnutls_deinit(*session);
	free(session);
}
